baseurl = "http://rickithadi.github.io/"
theme = "hugo-geo"
<<<<<<< HEAD
relativeURLs = false
languageCode = "en-us"
title = "My Site"
=======

relativeURLs = false
languageCode = "en-us"
title = "~~"
>>>>>>> 2e61028055bfd846552a72f7738211e5c3b5f2b8
disqusShortname = "shortcode-here"
paginate = 5

[taxonomies]
	tag = "tags"
	tutorial = "tutorials"

[params]
	showglobe = true

	favicon = "favicon.ico"
	
	analytics = "code-here"

	email = "rickithadi@gmail.com"

<<<<<<< HEAD
	profilepic = "img/randy.jpg"
	
	title = "Hadi Rickit"
	subtitle = "stuff"
=======
	profilepic = "img/profile.png"
	
	title = "Hadi Rickit"
	subtitle = "a blog thing"
>>>>>>> 2e61028055bfd846552a72f7738211e5c3b5f2b8

	# Social buttons for sidebar
	# Each of these are optional
	[[params.socialbuttons]]
	faicon = "github"
	url = "https://github.com/rickithadi"
	[[params.socialbuttons]]
	faicon = "instagram"
	url = "https://twitter.com/alexanderurq"
	[[params.socialbuttons]]
	faicon = "linkedin"
	url = "https://linkedin.com"
	[[params.socialbuttons]]
	faicon = "google-plus"
<<<<<<< HEAD
	url = "https://plus.google.com/+YourID"
=======
	url = "https://plus.google.com/rickithadi"
>>>>>>> 2e61028055bfd846552a72f7738211e5c3b5f2b8

	[[params.navlinks]]
	name = "About"
	url = "about"
	
	[[params.navlinks]]
	name = "Blog"
	url = ""
	
	[[params.navlinks]]
<<<<<<< HEAD
	name = "Tutorials"
=======
	name = "media??"
>>>>>>> 2e61028055bfd846552a72f7738211e5c3b5f2b8
	url = "tutorial/"
